import { cleanup } from '@testing-library/react';

import { handlers as customHandlers } from './customMock';
import { handlers as autoGeneratedHandlers } from './mock';
import { handlers as aclHandlers } from './portalMock';

import { setupWorker } from 'msw/browser';
import { afterEach, beforeAll, beforeEach } from 'vitest';

const worker = setupWorker(
  ...customHandlers,
  ...aclHandlers,
  ...autoGeneratedHandlers
);

beforeAll(() => {
  worker.start({
    quiet: true,
    onUnhandledRequest: (req, print) => {
      if (req.url.includes('api') && req.url.includes('https')) print.error();
      return;
    },
  });
});

beforeEach(() => {
  cleanup();
});

afterEach(() => {
  worker.resetHandlers();
});

export { worker };