name: E2E Tests
on:
  pull_request:
    branches: [main, next]
    paths:
      - "**"
      - ".github/workflows/**"
    types: [opened, reopened, synchronize, ready_for_review]
jobs:
  e2e:
    name: 'Test on ${{ matrix.project }}'
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}

    strategy:
      fail-fast: false
      matrix:
        project: [chromium, firefox]
        node-version: [21.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        working-directory: client
        run: bun install --frozen-lockfile

      - name: Install playwright
        working-directory: client
        run: bunx playwright install --with-deps

      - name: Run Playwright tests
        working-directory: client
        run: bunx playwright test -c playwright.config.ts --project=${{ matrix.project }}

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ matrix.project }}
          path: client/playwright-report/
          retention-days: 30
