name: Pull request

on:
  pull_request:
    branches:
      [main, master, develop, development, staging, release/**/*, hotfix/**/*]
    paths:
      - 'client/**'
      - '.github/workflows/**'
  workflow_dispatch:
jobs:
  eslint:
    name: ESLint
    uses: ./.github/workflows/eslint.yaml

  browser_tests:
    name: Browser tests
    uses: ./.github/workflows/browser_tests.yaml

  jsdom_tests:
    name: JSDOM tests
    uses: ./.github/workflows/jsdom_tests.yaml

  code_coverage:
    name: Code coverage
    uses: ./.github/workflows/code_coverage.yaml

  build:
    name: Build
    uses: ./.github/workflows/build.yaml

  build-docker:
    name: Build docker image
    uses: ./.github/workflows/build_docker.yaml

  check_configs:
    name: Check Config files
    uses: ./.github/workflows/check_config.yaml
