name: Pull request

on:
  pull_request:
    branches:
      [main, master, develop, development, staging, release/**/*, hotfix/**/*]
    paths:
      - 'client/**'
      - '.github/workflows/**'
  workflow_dispatch:
jobs:
  eslint:
    name: ESLint
    uses: ./eslint.yaml

  test:
    name: Test
    uses: ./test.yaml

  build:
    name: Build
    uses: ./build.yaml

  build-docker:
    name: Build docker image
    uses: ./build_docker.yaml

  check_configs:
    name: Check Config files
    uses: ./check_config.yaml
