name: Browser tests
on:
  workflow_call:
jobs:
  browser:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chromium]

    steps:
      - uses: actions/checkout@v4

      - name: Use bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Install playwright with dependencies
        run: bunx playwright install --with-deps ${{ matrix.browser }}

      - name: Tests
        run: bun run test:coverage-ci --project="browser (${{ matrix.browser }})"
        continue-on-error: true

      - uses: actions/cache@v4
        with:
          path: ./coverage
          key: browser-coverage
