name: "Tests"

on:
  workflow_call:

jobs:
  tests:
    name: Run tests
    uses: ./.github/workflows/tests.yaml

  coverage:
    runs-on: ubuntu-latest
    needs: [tests]

    permissions:
      # Required to checkout the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write

    steps:
      - uses: actions/cache@v4
        name: 'Get coverage report'
        with:
          path: ./coverage
          key: coverage

      - name: 'Report Coverage'
        # Set if: always() to also generate the report if tests are failing
        # Only works if you set `reportOnFailure: true` in your vite config as specified above
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          vite-config-path: ./vitest.config.ts