name: JSDOM tests
on:
  workflow_call:
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Tests
        run: bun run test:ci --project jsdom --coverage

      - uses: actions/cache@v4
        with:
          path: jsdom-coverage
          key: ${{ runner.os }}-jsdom-coverage
