name: 📣 Promote
on:
  workflow_call:
    inputs:
      environment-name:
        description: 'The GitHub environment to use this workflow in'
        type: string
        required: true
      from-environment:
        description: 'The Radix environment to promote from'
        type: string
        required: true
      to-environment:
        description: 'The Radix environment to promote to'
        type: string
        required: true
jobs:
  promote:
    environment:
      name: ${{ inputs.environment-name }}
    name: 📣 Promote
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: equinor/radix-github-actions@v2
        with:
          azure_client_id: ${{ vars.CLIENT_ID }}

      - run: rx create pipeline-job promote
          --application ${{ vars.RADIX_APPLICATION_NAME }}
          --follow
          --from-environment ${{ inputs.from-environment }}
          --to-environment ${{ inputs.to-environment }}
          --use-active-deployment