name: Pull request

on:
  pull_request:
    branches: [main, next]
    paths:
      - "**"
      - ".github/workflows/**"
  workflow_dispatch:
jobs:
  eslint:
    name: ESLint
    uses: ./.github/workflows/eslint.yaml

  tests:
    name: Test run
    uses: ./.github/workflows/code_coverage.yaml

  build:
    name: Build
    uses: ./.github/workflows/build.yaml

  build-storybook:
    name: Build storybook
    uses: ./.github/workflows/build_storybook.yaml
