name: Pull request

on:
  pull_request:
    branches: [main, next]
    paths:
      - "**"
      - ".github/workflows/**"
  workflow_dispatch:
jobs:
  eslint:
    name: ESLint
    uses: ./.github/workflows/eslint.yaml

  tests:
    name: Test run
    uses: ./.github/workflows/tests.yaml

  build:
    name: Build
    uses: ./.github/workflows/build.yaml

  build-storybook:
    name: Build storybook
    uses: ./.github/workflows/build_storybook.yaml

  build-deploy-feature-radix:
    if: ${{ startsWith(github.head_ref, 'feat') }}
    name: Build and deploy to feature env
    uses: ./.github/workflows/build_deploy_radix.yaml
    with:
      environment-name: feature
      to-environment: feature
      branch: ${{ github.head_ref }}
