name: Pull request

on:
  pull_request:
    branches: [main, next]
    paths:
      - "**"
      - ".github/workflows/**"
  workflow_dispatch:
jobs:
  eslint:
    name: ESLint
    uses: ./.github/workflows/eslint.yaml

  jsdom:
    name: JSDOM tests
    uses: ./.github/workflows/jsdom_tests.yaml

  browser:
    name: Browser tests
    uses: ./.github/workflows/browser_tests.yaml

  code-coverage:
    name: Code coverage
    uses: ./.github/workflows/code_coverage.yaml

  build:
    name: Build
    uses: ./.github/workflows/build.yaml

  build-storybook:
    name: Build storybook
    uses: ./.github/workflows/build_storybook.yaml
